// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerManager.Data.Context;

#nullable disable

namespace ServerManager.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230203135702_iniate")]
    partial class iniate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ServerManager.Data.User.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("sm_user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = 1,
                            Name = "admin",
                            Password = "xW2PqVk+e29mqX3T2aZAYPuBl5e4SKVeKDXfvU9XC9g="
                        });
                });

            modelBuilder.Entity("ServerManagerCore.Models.ServerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<bool>("Launched")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<int>("TypeServer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("sm_server");
                });
#pragma warning restore 612, 618
        }
    }
}
